---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    type: ci-cd
    author: suresh
<<<<<<< HEAD
spec: 
 replicas: 4
 selector:
   matchLabels: 
    type: appserver
 template:
   metadata:
     name: tomcat-pod
     labels: 
      type: appserver
      author: suresh
   spec:
      containers: 
        - name: tomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 9090
...

=======
spec:
  replicas: 4
  selector:
    matchLabels:
      type: appserver
      author: suresh
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
        author: suresh
    spec:
      containers:
        - name: tomcat
          image: tomee
          ports: 
           - containerPort: 8080
             hostPort: 9090
...
>>>>>>> a8f7858eaaa0de98cc28fab1fb123be5328334d3
