---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    type: ci-cd
    author: suresh
spec:
  replicas: 4
  selector:
    matchLabels:
      type: appserver
      author: suresh
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
        author: suresh
    spec:
      containers:
        - name: tomcat
          image: tomee
          ports: 
           - containerPort: 8080
             hostPort: 9090
...
