---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    type: redis
    author: suresh
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    type: redisapp
    author: suresh
...

