---
apiVersion: v1
kind: ReplicationController 
metadata:
  name: tomcat-rc
  labels: 
    type: ci-cd 
    author: suresh
spec:
  replicas: 3
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: webserver
        author: suresh
    spec:
      containers:
        - name: tomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 9090

...
