---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: result-app-deployment
 labels:
   type: resultapp
   author: suresh
spec:
 replicas: 2
 selector:
  matchLabels:
   type: resultapp
 template:
  metadata:
    name: result-pod
    labels:
      type: resultapp
      author: suresh
  spec:
    containers:
      - name: result
        image: dockersamples/examplevotingapp_result
...

