---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    author: suresh
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30010
  selector: 
   type: app-server1
...
