---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
  labels:
    author: suresh
spec:
  replicas: 2
  selector:
    matchLabels:
      author: suresh
  template:
    metadata:
      name: jenkins-pod
      labels:
        author: suresh
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 9090
      tolerations:
        - key: slave2
          operator: Equal
          value: sureshr
          effect: NoSchedule
...
