---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    type: voting
    author: suresh
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: votingapp
    author: suresh
...
