---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: redis-app-deployment
 labels:
  type: redis-app
  author: suresh
spec: 
 replicas: 2
 selector:
  matchLabels: 
    type: redis-app
 template:
  metadata:
   name: redis-pod
   labels:
     type: redis-app
     author: suresh
  spec:
   containers:
    - name: redisapp
      image: redis
...
