---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: result-app-deployment
 labels:
  type: result-app
  author: suresh
spec: 
 replicas: 2
 selector:
  matchLabels:
   type: result-app
 template:
  metadata:
   name: result-pod
   labels:
     type: result-app
     author: suresh
  spec:
   containers:
    - name: resultapp
      image: dockersamples/examplevotingapp_result
...
