---
apiVersion: v1
kind: Service
metadata:
 name: result-service
 labels: 
  author: suresh
spec:
 type: LoadBalancer
 ports:
   - targetPort: 80
     port: 80
     nodePort: 30012
 selector:
  type: result-app
  author: suresh
...
