---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: voting-app-deployment
 labels:
  type: voting-app
  author: suresh
spec: 
 replicas: 2
 selector:
  matchLabels: 
    type: voting-app
 template:
  metadata:
   name: voting-pod
   labels:
     type: voting-app
     author: suresh
  spec:
   containers:
    - name: votingapp
      image: dockersamples/examplevotingapp_vote
...
